version: '3.8'

services:
  radius-proxy:
    image: ghcr.io/essinghigh/radius-proxy:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-54567}:54567"
    environment:
      - NODE_ENV=production
      - ISSUER=http://auth.example.local:${HOST_PORT:-54567}
      - EMAIL_SUFFIX=example.com
      - RADIUS_HOST=radius.example.local
      - RADIUS_SECRET=secret
      - RADIUS_PORT=1812
      - REDIRECT_URIS=
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
        read_only: true
