# radius-proxy configuration

# OAuth client credentials
OAUTH_CLIENT_ID = "grafana"
OAUTH_CLIENT_SECRET = "secret"
OAUTH_CODE_TTL = 600
OAUTH_REFRESH_TOKEN_TTL = 7776000
REDIRECT_URIS = ["https://grafana.example.com/login/generic_oauth"]

# RADIUS server
RADIUS_HOST = "192.168.0.191"
RADIUS_SECRET = "testing123"
RADIUS_TIMEOUT = 5
# RADIUS attribute number for group assignment (default: 25 for Class attribute)
# Examples: 25 (Class), 136 (Management-Policy-Id), 26 (Vendor-Specific)
RADIUS_ASSIGNMENT = 25

# For Cisco-AVPair (Vendor-Specific Attribute), uncomment and configure:
# RADIUS_ASSIGNMENT = 26
# RADIUS_VENDOR_ID = 9
# RADIUS_VENDOR_TYPE = 1
# RADIUS_VALUE_PATTERN = "shell:roles=([^,\s]+)"

# For other vendor-specific attributes, set appropriate vendor ID and type
# RADIUS_VENDOR_ID = <vendor_id>
# RADIUS_VENDOR_TYPE = <vendor_type>
# RADIUS_VALUE_PATTERN = "<regex_pattern_with_capture_group>"

# Server binding
HTTP_HOST = "0.0.0.0"
HTTP_PORT = 54567
ISSUER = "https://auth.example.com"

# User Configuration
EMAIL_SUFFIX = "example.local"
PERMITTED_CLASSES = "admin_group,editor_group,user_group"
ADMIN_CLASSES = "admin_group"

# Team Mapping: map RADIUS class/group names to Grafana team IDs
GRAFANA_BASE_URL = "https://grafana.example.com"
GRAFANA_SA_TOKEN = "glsa_xyzabc123"
# Disable TLS certificate verification for Grafana API calls
# Set to true if using internal/self-signed certificates (e.g., internal enterprise CA)
# This temporarily disables certificate verification only during Grafana API requests
# ⚠️  WARNING: Only use in trusted networks! This disables certificate verification.
GRAFANA_INSECURE_TLS = false
CLASS_MAP = {
    example_class = [2,6],
    another_example_class = [2,9,23]
}