# radius-proxy configuration

# OAuth client credentials
OAUTH_CLIENT_ID = "grafana"
OAUTH_CLIENT_SECRET = "secret"
OAUTH_CODE_TTL = 600
OAUTH_REFRESH_TOKEN_TTL = 7776000
REDIRECT_URIS = ["https://grafana.example.com/login/generic_oauth"]

# RADIUS server
RADIUS_HOST = "192.168.0.191"
RADIUS_SECRET = "testing123"
RADIUS_TIMEOUT = 5

# Server binding
HTTP_HOST = "0.0.0.0"
HTTP_PORT = 3000
ISSUER = "https://auth.example.com"

# User Configuration
EMAIL_SUFFIX = "example.com"
PERMITTED_CLASSES = "admin_group,editor_group"
ADMIN_CLASSES = "admin_group"

# Team Mapping: map RADIUS class/group names to Grafana team IDs
GRAFANA_BASE_URL = "https://grafana.example.com"
GRAFANA_SA_TOKEN = "glsa_xyzabc123"
CLASS_MAP = {
    example_class = [2,6],
    another_example_class = [2,9,23]
}