# radius-proxy configuration
# NOTE: HOSTNAME was renamed to HTTP_HOST to make the meaning explicit.
# Backwards compatibility is maintained: the app still reads HOSTNAME if set.

# OAuth client credentials
OAUTH_CLIENT_ID = "grafana"
OAUTH_CLIENT_SECRET = "secret"

# RADIUS server
RADIUS_HOST = "192.168.0.191"
RADIUS_SECRET = "testing123"

# Server binding
HTTP_HOST = "0.0.0.0"
HTTP_PORT = 3000

# Public issuer (optional) - set this to your public HTTPS URL to force canonical external URLs
# Example: ISSUER = "https://auth.example.com"
ISSUER = "https://auth.example.com"
ISSUER = "auth.example.com"

# User Configuration
EMAIL_SUFFIX = "example.com"
PERMITTED_CLASSES = "admin_group"